# TH GITHUB ACTIONS TESTING
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      mockval: ${{ steps.setup.outputs.mockval }}

    env:
      # GPG config demo - should be handled through secrets?
      # GPG_KEYNAME: "${{secrets.GPG_KEYNAME}}"
      GPG_PASSPHRASE: "${{secrets.GPG_PASSPHRASE}}"
      GPG_PRIVATE_KEY: "${{secrets.GPG_PRIVATE_KEY}}"
      
      REPO_PATH: "$GITHUB_WORKSPACE" # $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
      MVN_DEPLOY_FLAGS: "-s $GITHUB_WORKSPACE/settings.xml -Dmaven.repo.local=$GITHUB_WORKSPACE/.m2 -Denv.CI_DEPLOY_PASSWORD=$GITHUB_TOKEN -Denv.CI_DEPLOY_USERNAME=$GITHUB_USER -Denv.GPG_KEYNAME=${{secrets.GPG_KEYNAME}} -Denv.GPG_PASSPHRASE=${{secrets.GPG_PASSPHRASE}}"
      MVN_BUILD_FLAGS: "-Dmaven.repo.local=$GITHUB_WORKSPACE/.m2"
      # GPG_IMPORT_COMMAND: "cat <(echo -e '${{GPG_PRIVATE_KEY}}') | gpg --batch --import"
      GEN_DEPLOY_POM_SCRIPT: "$GITHUB_WORKSPACE/rosetta-source/src/main/resources/build-resources/create-deploy-pom.sh"
      GEN_DEPLOY_POM_PY: "$GITHUB_WORKSPACE/rosetta-source/src/main/resources/build-resources/create-deploy-pom.py"
 
    steps:
      - name: main_clone
        uses: actions/checkout@v2
      
      - name: SetProperties
        shell: bash
        run: |
          myVAL="mockvalaa"
          echo "mockval=$myVAL" >> "$GITHUB_ENV"
          echo "REPO_PATH: ${{env.REPO_PATH}}"
          echo "MVN_DEPLOY_FLAGS: ${{env.MVN_DEPLOY_FLAGS}}"
          echo "MVN_BUILD_FLAGS: ${{env.MVN_BUILD_FLAGS}}"
          echo "::set-output name=mvn_build_flags::${{env.MVN_BUILD_FLAGS}}"
          echo "GPG_IMPORT_COMMAND: ${{env.GPG_IMPORT_COMMAND}}"
          echo "GEN_DEPLOY_POM_SCRIPT: ${{env.GEN_DEPLOY_POM_SCRIPT}}"
          echo "GEN_DEPLOY_POM_PY: ${{env.GEN_DEPLOY_POM_PY}}"
          echo "::set-output name=gpg_import_command::cat <(echo -e '${{secrets.GPG_PRIVATE_KEY}}') | gpg --batch --import"

          

      - name: ReleaseProperties
        #if: ${{ github.event_name == 'push' && github.event.ref_type == 'tag' }}
        shell: bash
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "${RELEASE_NAME_GO}" | sed 's|^refs/tags/||'
          echo "RELEASE_NAME: ${{env.RELEASE_NAME}}"
          echo "MAVEN_BUILD_PROFILES: ${{env.MAVEN_BUILD_PROFILES}}"
          echo "MVN_DEPLOY_FILE_FLAGS: ${{env.MVN_DEPLOY_FILE_FLAGS}}"
        env:
          RELEASE_NAME: "${{ github.ref }}" #TBD
          RELEASE_NAME_GO: ${{ github.ref }}
          MAVEN_BUILD_PROFILES: "daml,scala,typescript,golang,csharp8,csharp9,kotlin,python,full,gpg,excel"
          MVN_DEPLOY_FILE_FLAGS: "${{env.MVN_BUILD_FLAGS}} ${{env.MVN_DEPLOY_FLAGS}} -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2 -DrepositoryId=ossrh-distro -Dgpg.passphrase=${{env.GPG_PASSPHRASE}}"
          
      - name: SnapshotProperties
        if: ${{ github.event_name == 'push' && github.event.ref_type != 'tag' }}
        shell: bash
        run: |
          echo "RELEASE_NAME: ${{env.RELEASE_NAME}}"
          echo "MAVEN_BUILD_PROFILES: ${{env.MAVEN_BUILD_PROFILES}}"
          echo "MVN_DEPLOY_FILE_FLAGS: ${{env.MVN_DEPLOY_FILE_FLAGS}}"
        env:
          RELEASE_NAME: "${{ github.ref }}-SNAPSHOT" #how to get branch tag
          MAVEN_BUILD_PROFILES: "daml,scala,typescript,golang,csharp8,csharp9,kotlin,python,gpg,excel"
          MVN_DEPLOY_FILE_FLAGS: "${{env.MVN_BUILD_FLAGS}} ${{env.MVN_DEPLOY_FLAGS}} -Durl=https://oss.sonatype.org/content/repositories/snapshots -DrepositoryId=ossrh -Dgpg.passphrase=${{env.GPG_PASSPHRASE}}"

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Import GPG Key
        run: |
          # Your GPG import command goes here
          # Example: echo "${GPG_PRIVATE_KEY}" | gpg --batch --import
          MOCKVAL="${{ needs.setup.outputs.mockval }}"
          echo "${{ needs.setup.mockval }}"
          echo "::add-mask::$RETRIEVED_SECRET"
          echo "${{ needs.setup.outputs.gpg_import_command }}"
      - name: Maven build
        #working-directory: ../../
        run: |
          echo ${{ needs.setup.outputs.mvn_build_flags }}
          pwd
          ls -la
          echo "RELEASE_NAME: ${{env.RELEASE_NAME}}"
          echo "MVN_BUILD_FLAGS: ${{env.MVN_BUILD_FLAGS}}"
          echo "REPO_PATH: ${{env.REPO_PATH}}"
          mvn ${{ env.MVN_BUILD_FLAGS }} versions:set -DnewVersion=${{ env.RELEASE_NAME }} versions:update-child-modules -DallowSnapshots=true
          mvn ${{ env.MVN_DEPLOY_FLAGS }} clean deploy -P "${{ env.MAVEN_BUILD_PROFILES }}"
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          MVN_BUILD_FLAGS: ${{ env.MVN_BUILD_FLAGS }}
          RELEASE_NAME: ${{ env.RELEASE_NAME }}
          MVN_DEPLOY_FLAGS: ${{ env.MVN_DEPLOY_FLAGS }}
          MAVEN_BUILD_PROFILES: ${{ env.MAVEN_BUILD_PROFILES }}
  
  distribute:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Steps for distribution if needed
      - name: Build CI
        run:
          echo "Testing distribute ci"
  
  finalise:
    needs: distribute
    runs-on: ubuntu-latest

    steps:
      # Steps for finalizing the process if needed
      - name: Build CI
        run:
          echo "Testing finalize ci"
